-- --------------------------------------------------------------------------
-- 0002 — tables
--
-- GENERATED by scripts/gen-schema.mjs from the base44 app definition.
-- Do not edit by hand — add a later migration instead.
-- --------------------------------------------------------------------------

-- School
create table public.schools (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text,
  country text,
  city text,
  address text,
  email text,
  phone text,
  logo_url text,
  curriculum text default 'ib_dp',
  plan text default 'starter',
  status text default 'onboarding',
  max_students numeric,
  max_users numeric default 100,
  modules_enabled text[],
  academic_year_start_month numeric default 9,
  timezone text default 'UTC',
  stripe_customer_id text,
  stripe_subscription_id text,
  billing_status text,
  trial_end_date timestamptz,
  subscription_current_period_end timestamptz,
  subscription_cancel_at_period_end boolean default false,
  billing_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint schools_curriculum_check check (curriculum is null or curriculum in ('ib_dp', 'ib_myp', 'ib_pyp', 'igcse', 'a_levels', 'us_common_core', 'custom')),
  constraint schools_plan_check check (plan is null or plan in ('starter', 'growth', 'enterprise')),
  constraint schools_status_check check (status is null or status in ('active', 'suspended', 'onboarding', 'cancelled')),
  constraint schools_billing_status_check check (billing_status is null or billing_status in ('trial', 'active', 'past_due', 'canceled', 'unpaid', 'incomplete'))
);


create trigger schools_set_updated_at before update on public.schools
  for each row execute function public.set_updated_at();

-- AcademicYear
create table public.academic_years (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  name text not null,
  start_date date,
  end_date date,
  is_current boolean default false,
  status text default 'planning',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint academic_years_status_check check (status is null or status in ('active', 'archived', 'planning'))
);

create index academic_years_school_id_idx on public.academic_years (school_id);
create index academic_years_school_created_idx on public.academic_years (school_id, created_at desc);

create trigger academic_years_set_updated_at before update on public.academic_years
  for each row execute function public.set_updated_at();

-- Term
create table public.terms (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  academic_year_id uuid references public.academic_years(id) on delete set null,
  name text not null,
  start_date date,
  end_date date,
  is_current boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index terms_school_id_idx on public.terms (school_id);
create index terms_academic_year_id_idx on public.terms (academic_year_id);
create index terms_school_created_idx on public.terms (school_id, created_at desc);

create trigger terms_set_updated_at before update on public.terms
  for each row execute function public.set_updated_at();

-- Subject
create table public.subjects (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  name text not null,
  code text,
  ib_group text,
  level text default 'na',
  status text default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint subjects_ib_group_check check (ib_group is null or ib_group in ('group1_language_literature', 'group2_language_acquisition', 'group3_individuals_societies', 'group4_sciences', 'group5_mathematics', 'group6_arts', 'core_tok', 'core_ee', 'core_cas')),
  constraint subjects_level_check check (level is null or level in ('HL', 'SL', 'core', 'na')),
  constraint subjects_status_check check (status is null or status in ('active', 'archived'))
);

create index subjects_school_id_idx on public.subjects (school_id);
create index subjects_school_created_idx on public.subjects (school_id, created_at desc);

create trigger subjects_set_updated_at before update on public.subjects
  for each row execute function public.set_updated_at();

-- Cohort
create table public.cohorts (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  name text not null,
  type text not null default 'custom',
  academic_year_id uuid references public.academic_years(id) on delete set null,
  student_ids uuid[],
  description text,
  color text,
  status text default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint cohorts_type_check check (type is null or type in ('dp1', 'dp2', 'myp', 'advisory', 'hl_sl_group', 'intervention', 'custom')),
  constraint cohorts_status_check check (status is null or status in ('active', 'archived'))
);

create index cohorts_school_id_idx on public.cohorts (school_id);
create index cohorts_academic_year_id_idx on public.cohorts (academic_year_id);
create index cohorts_school_created_idx on public.cohorts (school_id, created_at desc);

create trigger cohorts_set_updated_at before update on public.cohorts
  for each row execute function public.set_updated_at();

-- Room
create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  name text not null,
  code text,
  building text,
  capacity numeric,
  room_type text default 'classroom',
  facilities text[],
  status text default 'active',
  external_sync_id text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint rooms_room_type_check check (room_type is null or room_type in ('classroom', 'lab', 'gym', 'library', 'auditorium', 'office', 'other')),
  constraint rooms_status_check check (status is null or status in ('active', 'maintenance', 'unavailable'))
);

create index rooms_school_id_idx on public.rooms (school_id);
create index rooms_school_created_idx on public.rooms (school_id, created_at desc);

create trigger rooms_set_updated_at before update on public.rooms
  for each row execute function public.set_updated_at();

-- Period
create table public.periods (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  name text not null,
  start_time text not null,
  end_time text not null,
  day_of_week numeric,
  period_order numeric,
  is_break boolean default false,
  academic_year_id uuid references public.academic_years(id) on delete set null,
  external_sync_id text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index periods_school_id_idx on public.periods (school_id);
create index periods_academic_year_id_idx on public.periods (academic_year_id);
create index periods_school_created_idx on public.periods (school_id, created_at desc);

create trigger periods_set_updated_at before update on public.periods
  for each row execute function public.set_updated_at();

-- Class
create table public.classes (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  subject_id uuid references public.subjects(id) on delete set null,
  academic_year_id uuid references public.academic_years(id) on delete set null,
  cohort_id uuid references public.cohorts(id) on delete set null,
  name text not null,
  section text,
  capacity numeric,
  roster_locked boolean default false,
  teacher_ids uuid[],
  primary_teacher_id uuid references public.profiles(id) on delete set null,
  co_teacher_permissions jsonb,
  student_ids uuid[],
  subject_teacher_assignments jsonb,
  schedule_info text,
  room text,
  status text default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint classes_status_check check (status is null or status in ('active', 'archived'))
);

create index classes_school_id_idx on public.classes (school_id);
create index classes_subject_id_idx on public.classes (subject_id);
create index classes_academic_year_id_idx on public.classes (academic_year_id);
create index classes_cohort_id_idx on public.classes (cohort_id);
create index classes_primary_teacher_id_idx on public.classes (primary_teacher_id);
create index classes_school_created_idx on public.classes (school_id, created_at desc);

create trigger classes_set_updated_at before update on public.classes
  for each row execute function public.set_updated_at();

-- CurriculumTopic
create table public.curriculum_topics (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  subject_id uuid references public.subjects(id) on delete restrict not null,
  parent_topic_id uuid references public.curriculum_topics(id) on delete set null,
  level text not null default 'topic',
  title text not null,
  description text,
  code text,
  sequence numeric default 0,
  status text default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint curriculum_topics_level_check check (level is null or level in ('topic', 'subtopic')),
  constraint curriculum_topics_status_check check (status is null or status in ('active', 'archived'))
);

create index curriculum_topics_school_id_idx on public.curriculum_topics (school_id);
create index curriculum_topics_subject_id_idx on public.curriculum_topics (subject_id);
create index curriculum_topics_parent_topic_id_idx on public.curriculum_topics (parent_topic_id);
create index curriculum_topics_school_created_idx on public.curriculum_topics (school_id, created_at desc);

create trigger curriculum_topics_set_updated_at before update on public.curriculum_topics
  for each row execute function public.set_updated_at();

-- Assignment
create table public.assignments (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  class_id uuid references public.classes(id) on delete restrict not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  title text not null,
  description text,
  type text default 'homework',
  due_date timestamptz,
  publish_date timestamptz,
  max_score numeric,
  ib_criteria text[],
  attachments text[],
  curriculum_topic_ids uuid[],
  status text default 'draft',
  allow_late boolean default true,
  primary_submission_format text,
  allow_alternative_formats boolean default false,
  alternative_formats text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint assignments_type_check check (type is null or type in ('homework', 'essay', 'lab_report', 'presentation', 'exam', 'project', 'quiz', 'other')),
  constraint assignments_status_check check (status is null or status in ('draft', 'published', 'closed', 'archived')),
  constraint assignments_primary_submission_format_check check (primary_submission_format is null or primary_submission_format in ('google_doc', 'google_slides', 'google_sheet', 'file_upload', 'link'))
);

create index assignments_school_id_idx on public.assignments (school_id);
create index assignments_class_id_idx on public.assignments (class_id);
create index assignments_teacher_id_idx on public.assignments (teacher_id);
create index assignments_school_created_idx on public.assignments (school_id, created_at desc);

create trigger assignments_set_updated_at before update on public.assignments
  for each row execute function public.set_updated_at();

-- Assessment
create table public.assessments (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  class_id uuid references public.classes(id) on delete restrict not null,
  assignment_id uuid references public.assignments(id) on delete set null,
  title text not null,
  description text,
  type text not null,
  duration_minutes numeric,
  status text default 'draft',
  max_score numeric,
  questions jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint assessments_type_check check (type is null or type in ('quiz', 'exam')),
  constraint assessments_status_check check (status is null or status in ('draft', 'published', 'closed'))
);

create index assessments_school_id_idx on public.assessments (school_id);
create index assessments_class_id_idx on public.assessments (class_id);
create index assessments_assignment_id_idx on public.assessments (assignment_id);
create index assessments_school_created_idx on public.assessments (school_id, created_at desc);

create trigger assessments_set_updated_at before update on public.assessments
  for each row execute function public.set_updated_at();

-- Submission
create table public.submissions (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  assignment_id uuid references public.assignments(id) on delete restrict not null,
  class_id uuid references public.classes(id) on delete set null,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  content text,
  file_urls text[],
  link_url text,
  documents jsonb,
  version_number numeric default 1,
  submission_time timestamptz,
  file_type text,
  previous_submission_id uuid references public.submissions(id) on delete set null,
  is_current_version boolean default true,
  annotations jsonb,
  status text default 'draft',
  submitted_at timestamptz,
  score numeric,
  feedback text,
  graded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint submissions_status_check check (status is null or status in ('draft', 'submitted', 'late', 'graded', 'returned', 'resubmitted'))
);

create index submissions_school_id_idx on public.submissions (school_id);
create index submissions_assignment_id_idx on public.submissions (assignment_id);
create index submissions_class_id_idx on public.submissions (class_id);
create index submissions_student_id_idx on public.submissions (student_id);
create index submissions_previous_submission_id_idx on public.submissions (previous_submission_id);
create index submissions_school_created_idx on public.submissions (school_id, created_at desc);

create trigger submissions_set_updated_at before update on public.submissions
  for each row execute function public.set_updated_at();

-- AccountState
create table public.account_states (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete restrict not null,
  user_email text not null,
  account_status text not null default 'invited',
  school_id uuid references public.schools(id) on delete cascade,
  school_name text,
  role text,
  invitation_token text,
  invitation_accepted_at timestamptz,
  first_login_at timestamptz,
  last_login_at timestamptz,
  profile_completed boolean default false,
  profile_completion_required_fields text[],
  password_reset_token text,
  password_reset_expires_at timestamptz,
  password_set_at timestamptz,
  suspended_reason text,
  suspended_at timestamptz,
  suspended_by text,
  email_verified boolean default false,
  email_verified_at timestamptz,
  login_attempts numeric default 0,
  locked_until timestamptz,
  onboarding_step text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint account_states_account_status_check check (account_status is null or account_status in ('invited', 'pending_activation', 'active', 'suspended', 'deactivated', 'incomplete_profile')),
  constraint account_states_role_check check (role is null or role in ('school_admin', 'ib_coordinator', 'teacher', 'student', 'parent')),
  constraint account_states_onboarding_step_check check (onboarding_step is null or onboarding_step in ('accept_invitation', 'set_password', 'complete_profile', 'verify_email', 'complete'))
);

create index account_states_user_id_idx on public.account_states (user_id);
create index account_states_school_id_idx on public.account_states (school_id);
create index account_states_school_created_idx on public.account_states (school_id, created_at desc);

create trigger account_states_set_updated_at before update on public.account_states
  for each row execute function public.set_updated_at();

-- AssessmentSubmission
create table public.assessment_submissions (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  assessment_id uuid references public.assessments(id) on delete restrict not null,
  assignment_id uuid references public.assignments(id) on delete set null,
  class_id uuid references public.classes(id) on delete restrict not null,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  answers jsonb,
  status text default 'in_progress',
  started_at timestamptz,
  submitted_at timestamptz,
  time_remaining_seconds numeric,
  total_score numeric,
  max_score numeric,
  needs_teacher_review boolean default false,
  locked boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint assessment_submissions_status_check check (status is null or status in ('in_progress', 'submitted', 'auto_graded', 'reviewed'))
);

create index assessment_submissions_school_id_idx on public.assessment_submissions (school_id);
create index assessment_submissions_assessment_id_idx on public.assessment_submissions (assessment_id);
create index assessment_submissions_assignment_id_idx on public.assessment_submissions (assignment_id);
create index assessment_submissions_class_id_idx on public.assessment_submissions (class_id);
create index assessment_submissions_student_id_idx on public.assessment_submissions (student_id);
create index assessment_submissions_school_created_idx on public.assessment_submissions (school_id, created_at desc);

create trigger assessment_submissions_set_updated_at before update on public.assessment_submissions
  for each row execute function public.set_updated_at();

-- AttendancePolicy
create table public.attendance_policies (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  codes jsonb default '[]'::jsonb,
  reason_categories jsonb default '[]'::jsonb,
  require_reason_for_absence boolean default false,
  require_correction_reason boolean default true,
  chronic_absence_threshold_percent numeric default 20,
  frequent_lateness_threshold numeric default 3,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index attendance_policies_school_id_idx on public.attendance_policies (school_id);
create index attendance_policies_school_created_idx on public.attendance_policies (school_id, created_at desc);

create trigger attendance_policies_set_updated_at before update on public.attendance_policies
  for each row execute function public.set_updated_at();

-- AttendanceRecord
create table public.attendance_records (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  class_id uuid references public.classes(id) on delete restrict not null,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  date date not null,
  status text not null default 'present',
  note text,
  reason_category text,
  recorded_by text,
  correction_history jsonb default '[]'::jsonb,
  last_corrected_at timestamptz,
  last_corrected_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint attendance_records_status_check check (status is null or status in ('present', 'absent', 'late', 'excused'))
);

create index attendance_records_school_id_idx on public.attendance_records (school_id);
create index attendance_records_class_id_idx on public.attendance_records (class_id);
create index attendance_records_student_id_idx on public.attendance_records (student_id);
create index attendance_records_school_created_idx on public.attendance_records (school_id, created_at desc);

create trigger attendance_records_set_updated_at before update on public.attendance_records
  for each row execute function public.set_updated_at();

-- AuditLog
create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  user_email text,
  action text not null,
  entity_type text,
  entity_id uuid,
  details text,
  level text default 'info',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint audit_logs_level_check check (level is null or level in ('info', 'warning', 'critical'))
);

create index audit_logs_school_id_idx on public.audit_logs (school_id);
create index audit_logs_user_id_idx on public.audit_logs (user_id);
create index audit_logs_school_created_idx on public.audit_logs (school_id, created_at desc);

create trigger audit_logs_set_updated_at before update on public.audit_logs
  for each row execute function public.set_updated_at();

-- BehaviorPolicy
create table public.behavior_policies (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  incident_types jsonb default '[]'::jsonb,
  severity_levels jsonb default '[]'::jsonb,
  allow_teacher_visibility_override boolean default true,
  pastoral_roles text[] default array['school_admin', 'ib_coordinator']::text[],
  require_action_for_severity text[] default '{}'::text[],
  follow_up_tracking_enabled boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index behavior_policies_school_id_idx on public.behavior_policies (school_id);
create index behavior_policies_school_created_idx on public.behavior_policies (school_id, created_at desc);

create trigger behavior_policies_set_updated_at before update on public.behavior_policies
  for each row execute function public.set_updated_at();

-- BehaviorRecord
create table public.behavior_records (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  class_id uuid references public.classes(id) on delete set null,
  recorded_by text,
  recorded_by_name text,
  type text default 'note',
  incident_type_id text,
  category text,
  title text not null,
  description text,
  date date not null,
  severity text,
  visible_to_student boolean default false,
  visible_to_parent boolean default false,
  staff_only boolean default false,
  action_taken text,
  follow_up_required boolean default false,
  follow_up_completed boolean default false,
  follow_up_note text,
  pastoral_reviewed boolean default false,
  pastoral_reviewed_by text,
  pastoral_reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint behavior_records_type_check check (type is null or type in ('positive', 'concern', 'incident', 'note')),
  constraint behavior_records_category_check check (category is null or category in ('academic', 'social', 'conduct', 'participation', 'achievement', 'attendance_related', 'safety', 'other')),
  constraint behavior_records_severity_check check (severity is null or severity in ('low', 'medium', 'high', 'critical'))
);

create index behavior_records_school_id_idx on public.behavior_records (school_id);
create index behavior_records_student_id_idx on public.behavior_records (student_id);
create index behavior_records_class_id_idx on public.behavior_records (class_id);
create index behavior_records_school_created_idx on public.behavior_records (school_id, created_at desc);

create trigger behavior_records_set_updated_at before update on public.behavior_records
  for each row execute function public.set_updated_at();

-- CASExperience
create table public.cas_experiences (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  title text not null,
  description text,
  cas_strands text[] not null,
  learning_outcomes text[],
  start_date date,
  end_date date,
  status text default 'planned',
  hours numeric,
  evidence_urls text[],
  reflection text,
  supervisor_name text,
  supervisor_email text,
  coordinator_feedback text,
  coordinator_approved_by text,
  coordinator_approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint cas_experiences_status_check check (status is null or status in ('planned', 'ongoing', 'completed', 'approved'))
);

create index cas_experiences_school_id_idx on public.cas_experiences (school_id);
create index cas_experiences_student_id_idx on public.cas_experiences (student_id);
create index cas_experiences_school_created_idx on public.cas_experiences (school_id, created_at desc);

create trigger cas_experiences_set_updated_at before update on public.cas_experiences
  for each row execute function public.set_updated_at();

-- ClassMaterial
create table public.class_materials (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  class_id uuid references public.classes(id) on delete restrict not null,
  title text not null,
  description text,
  type text not null default 'file',
  url text not null,
  file_name text,
  file_size numeric,
  mime_type text,
  uploaded_by_id uuid references public.profiles(id) on delete set null,
  uploaded_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint class_materials_type_check check (type is null or type in ('file', 'link'))
);

create index class_materials_school_id_idx on public.class_materials (school_id);
create index class_materials_class_id_idx on public.class_materials (class_id);
create index class_materials_uploaded_by_id_idx on public.class_materials (uploaded_by_id);
create index class_materials_school_created_idx on public.class_materials (school_id, created_at desc);

create trigger class_materials_set_updated_at before update on public.class_materials
  for each row execute function public.set_updated_at();

-- DemoRequest
create table public.demo_requests (
  id uuid primary key default gen_random_uuid(),
  school_name text not null,
  contact_name text not null,
  email text not null,
  phone text,
  country text,
  school_size text,
  message text,
  status text default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint demo_requests_school_size_check check (school_size is null or school_size in ('small_under_200', 'medium_200_500', 'large_500_1000', 'xlarge_over_1000')),
  constraint demo_requests_status_check check (status is null or status in ('new', 'contacted', 'demo_scheduled', 'converted', 'declined'))
);


create trigger demo_requests_set_updated_at before update on public.demo_requests
  for each row execute function public.set_updated_at();

-- EEMilestone
create table public.ee_milestones (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  supervisor_id uuid references public.profiles(id) on delete set null,
  supervisor_name text,
  subject_area text,
  research_question text,
  milestone_type text not null,
  due_date date,
  submission_date timestamptz,
  status text default 'pending',
  draft_url text,
  student_notes text,
  supervisor_feedback text,
  supervisor_feedback_date timestamptz,
  word_count numeric,
  meeting_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint ee_milestones_milestone_type_check check (milestone_type is null or milestone_type in ('initial_proposal', 'first_meeting', 'research_planning', 'first_draft', 'interim_reflection', 'second_draft', 'final_draft', 'viva_voce')),
  constraint ee_milestones_status_check check (status is null or status in ('pending', 'submitted', 'reviewed', 'approved', 'needs_revision'))
);

create index ee_milestones_school_id_idx on public.ee_milestones (school_id);
create index ee_milestones_student_id_idx on public.ee_milestones (student_id);
create index ee_milestones_supervisor_id_idx on public.ee_milestones (supervisor_id);
create index ee_milestones_school_created_idx on public.ee_milestones (school_id, created_at desc);

create trigger ee_milestones_set_updated_at before update on public.ee_milestones
  for each row execute function public.set_updated_at();

-- ErrorLog
create table public.error_logs (
  id uuid primary key default gen_random_uuid(),
  message text not null,
  code text not null,
  context text,
  severity text default 'error',
  user_id uuid references public.profiles(id) on delete set null,
  school_id uuid references public.schools(id) on delete cascade,
  stack_trace text,
  timestamp timestamptz,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint error_logs_severity_check check (severity is null or severity in ('info', 'warning', 'error', 'critical'))
);

create index error_logs_user_id_idx on public.error_logs (user_id);
create index error_logs_school_id_idx on public.error_logs (school_id);
create index error_logs_school_created_idx on public.error_logs (school_id, created_at desc);

create trigger error_logs_set_updated_at before update on public.error_logs
  for each row execute function public.set_updated_at();

-- GoogleConnection
create table public.google_connections (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete restrict not null,
  user_email text,
  status text not null default 'disconnected',
  google_email text,
  token_expiry timestamptz,
  scopes text[],
  last_verified_at timestamptz,
  last_error text,
  error_code text,
  reconnection_required boolean default false,
  failed_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint google_connections_status_check check (status is null or status in ('connected', 'disconnected', 'expired', 'revoked', 'permission_denied')),
  constraint google_connections_error_code_check check (error_code is null or error_code in ('token_expired', 'invalid_grant', 'access_denied', 'network_error', 'scope_mismatch', 'revoked', 'unknown'))
);

create index google_connections_school_id_idx on public.google_connections (school_id);
create index google_connections_user_id_idx on public.google_connections (user_id);
create index google_connections_school_created_idx on public.google_connections (school_id, created_at desc);

create trigger google_connections_set_updated_at before update on public.google_connections
  for each row execute function public.set_updated_at();

-- GovernancePolicy
create table public.governance_policies (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  reason_enforcement jsonb,
  retention jsonb,
  privacy jsonb,
  audit jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index governance_policies_school_id_idx on public.governance_policies (school_id);
create index governance_policies_school_created_idx on public.governance_policies (school_id, created_at desc);

create trigger governance_policies_set_updated_at before update on public.governance_policies
  for each row execute function public.set_updated_at();

-- GradeItem
create table public.grade_items (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  class_id uuid references public.classes(id) on delete restrict not null,
  student_id uuid references public.profiles(id) on delete set null,
  student_name text,
  assignment_id uuid references public.assignments(id) on delete set null,
  title text not null,
  score numeric,
  max_score numeric,
  percentage numeric,
  ib_grade numeric,
  comment text,
  status text default 'draft',
  visible_to_student boolean default false,
  visible_to_parent boolean default false,
  term_id uuid references public.terms(id) on delete set null,
  grading_type text default 'simple',
  rubric_criteria jsonb,
  criterion_scores jsonb,
  is_template boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint grade_items_status_check check (status is null or status in ('draft', 'published', 'missing', 'late', 'excused')),
  constraint grade_items_grading_type_check check (grading_type is null or grading_type in ('simple', 'rubric'))
);

create index grade_items_school_id_idx on public.grade_items (school_id);
create index grade_items_class_id_idx on public.grade_items (class_id);
create index grade_items_student_id_idx on public.grade_items (student_id);
create index grade_items_assignment_id_idx on public.grade_items (assignment_id);
create index grade_items_term_id_idx on public.grade_items (term_id);
create index grade_items_school_created_idx on public.grade_items (school_id, created_at desc);

create trigger grade_items_set_updated_at before update on public.grade_items
  for each row execute function public.set_updated_at();

-- GradebookPolicy
create table public.gradebook_policies (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  grading_model text default 'points_based',
  categories jsonb default '[]'::jsonb,
  allow_teacher_category_override boolean default true,
  default_visible_to_student boolean default false,
  default_visible_to_parent boolean default false,
  feedback_only_mode boolean default false,
  grade_release_mode text default 'teacher_controlled',
  scheduled_release_date timestamptz,
  allow_teacher_visibility_override boolean default true,
  reporting_windows jsonb default '[]'::jsonb,
  lock_grades_after_deadline boolean default false,
  require_justification_for_locked_edit boolean default false,
  justification_min_chars numeric default 20,
  admin_can_override_lock boolean default true,
  predicted_grades_enabled boolean default true,
  predicted_grade_entry_roles text[] default array['teacher', 'ib_coordinator']::text[],
  predicted_grades_require_rationale boolean default true,
  coordinator_can_lock_predicted boolean default true,
  predicted_grades_locked boolean default false,
  predicted_grades_released_to_student boolean default false,
  predicted_grades_released_to_parent boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint gradebook_policies_grading_model_check check (grading_model is null or grading_model in ('points_based', 'category_weights', 'ib_criteria_only')),
  constraint gradebook_policies_grade_release_mode_check check (grade_release_mode is null or grade_release_mode in ('immediate', 'teacher_controlled', 'scheduled', 'coordinator_release'))
);

create index gradebook_policies_school_id_idx on public.gradebook_policies (school_id);
create index gradebook_policies_school_created_idx on public.gradebook_policies (school_id, created_at desc);

create trigger gradebook_policies_set_updated_at before update on public.gradebook_policies
  for each row execute function public.set_updated_at();

-- LessonPlan
create table public.lesson_plans (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  class_id uuid references public.classes(id) on delete restrict not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  title text not null,
  date date not null,
  duration_minutes numeric default 60,
  topics text[] default '{}'::text[],
  objectives text,
  notes text,
  resources jsonb default '[]'::jsonb,
  status text default 'planned',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint lesson_plans_status_check check (status is null or status in ('planned', 'completed'))
);

create index lesson_plans_school_id_idx on public.lesson_plans (school_id);
create index lesson_plans_class_id_idx on public.lesson_plans (class_id);
create index lesson_plans_teacher_id_idx on public.lesson_plans (teacher_id);
create index lesson_plans_school_created_idx on public.lesson_plans (school_id, created_at desc);

create trigger lesson_plans_set_updated_at before update on public.lesson_plans
  for each row execute function public.set_updated_at();

-- Message
create table public.messages (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete restrict not null,
  sender_name text,
  sender_role text,
  recipient_ids uuid[],
  subject text not null,
  body text not null,
  class_id uuid references public.classes(id) on delete set null,
  class_name text,
  thread_id uuid,
  is_announcement boolean default false,
  is_school_wide boolean default false,
  is_pinned boolean default false,
  read_by text[],
  attachments text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index messages_school_id_idx on public.messages (school_id);
create index messages_sender_id_idx on public.messages (sender_id);
create index messages_class_id_idx on public.messages (class_id);
create index messages_school_created_idx on public.messages (school_id, created_at desc);

create trigger messages_set_updated_at before update on public.messages
  for each row execute function public.set_updated_at();

-- MessagingPolicy
create table public.messaging_policies (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  permission_rules jsonb,
  broadcast_rules jsonb,
  announcement_governance jsonb,
  quiet_hours jsonb,
  notification_defaults jsonb,
  compliance jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index messaging_policies_school_id_idx on public.messaging_policies (school_id);
create index messaging_policies_school_created_idx on public.messaging_policies (school_id, created_at desc);

create trigger messaging_policies_set_updated_at before update on public.messaging_policies
  for each row execute function public.set_updated_at();

-- Notification
create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete restrict not null,
  message text not null,
  type text not null,
  timestamp timestamptz not null,
  read_status boolean default false,
  related_entity_id uuid,
  related_entity_type text,
  group_key text,
  group_count numeric default 1,
  email_sent boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint notifications_type_check check (type is null or type in ('assignment_created', 'assignment_due_soon', 'assignment_missing', 'grade_published', 'attendance_issue')),
  constraint notifications_related_entity_type_check check (related_entity_type is null or related_entity_type in ('Assignment', 'GradeItem', 'AttendanceRecord', 'Submission', 'Class', 'Message', 'Other'))
);

create index notifications_school_id_idx on public.notifications (school_id);
create index notifications_user_id_idx on public.notifications (user_id);
create index notifications_school_created_idx on public.notifications (school_id, created_at desc);

create trigger notifications_set_updated_at before update on public.notifications
  for each row execute function public.set_updated_at();

-- ParentStudentLink
create table public.parent_student_links (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  parent_id uuid references public.profiles(id) on delete restrict not null,
  parent_name text,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  relationship text default 'guardian',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint parent_student_links_relationship_check check (relationship is null or relationship in ('mother', 'father', 'guardian', 'other'))
);

create index parent_student_links_school_id_idx on public.parent_student_links (school_id);
create index parent_student_links_parent_id_idx on public.parent_student_links (parent_id);
create index parent_student_links_student_id_idx on public.parent_student_links (student_id);
create index parent_student_links_school_created_idx on public.parent_student_links (school_id, created_at desc);

create trigger parent_student_links_set_updated_at before update on public.parent_student_links
  for each row execute function public.set_updated_at();

-- PlatformConfig
create table public.platform_config (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  default_trial_days numeric default 30,
  default_notification_email text,
  allow_school_brand_overrides boolean default true,
  theme_mode text default 'light',
  default_primary_color text default '#4f46e5',
  default_accent_color text default '#0f172a',
  default_logo_url text,
  notifications jsonb,
  integration_settings jsonb,
  global_feature_flags jsonb,
  school_feature_overrides jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint platform_config_theme_mode_check check (theme_mode is null or theme_mode in ('light', 'dark', 'system'))
);


create trigger platform_config_set_updated_at before update on public.platform_config
  for each row execute function public.set_updated_at();

-- PredictedGrade
create table public.predicted_grades (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  student_id uuid references public.profiles(id) on delete restrict not null,
  student_name text,
  class_id uuid references public.classes(id) on delete restrict not null,
  class_name text,
  subject_id uuid references public.subjects(id) on delete set null,
  subject_name text,
  teacher_id uuid references public.profiles(id) on delete set null,
  teacher_name text,
  predicted_ib_grade numeric not null,
  confidence_level text default 'medium',
  rationale text,
  academic_year_id uuid references public.academic_years(id) on delete set null,
  term_id uuid references public.terms(id) on delete set null,
  entry_date date,
  visible_to_student boolean default false,
  visible_to_parent boolean default false,
  coordinator_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint predicted_grades_confidence_level_check check (confidence_level is null or confidence_level in ('low', 'medium', 'high'))
);

create index predicted_grades_school_id_idx on public.predicted_grades (school_id);
create index predicted_grades_student_id_idx on public.predicted_grades (student_id);
create index predicted_grades_class_id_idx on public.predicted_grades (class_id);
create index predicted_grades_subject_id_idx on public.predicted_grades (subject_id);
create index predicted_grades_teacher_id_idx on public.predicted_grades (teacher_id);
create index predicted_grades_academic_year_id_idx on public.predicted_grades (academic_year_id);
create index predicted_grades_term_id_idx on public.predicted_grades (term_id);
create index predicted_grades_school_created_idx on public.predicted_grades (school_id, created_at desc);

create trigger predicted_grades_set_updated_at before update on public.predicted_grades
  for each row execute function public.set_updated_at();

-- PrivacyRequest
create table public.privacy_requests (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  request_type text not null,
  requester_name text,
  requester_email text not null,
  requester_role text not null,
  subject_user_id uuid references public.profiles(id) on delete set null,
  subject_name text,
  description text,
  status text default 'pending',
  priority text default 'normal',
  due_date date,
  assigned_to text,
  assigned_to_name text,
  resolution_notes text,
  identity_verified boolean default false,
  acknowledged_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint privacy_requests_request_type_check check (request_type is null or request_type in ('data_export', 'account_deletion', 'anonymization', 'data_correction', 'access_request')),
  constraint privacy_requests_requester_role_check check (requester_role is null or requester_role in ('student', 'parent', 'teacher', 'staff', 'external')),
  constraint privacy_requests_status_check check (status is null or status in ('pending', 'acknowledged', 'in_progress', 'completed', 'rejected', 'withdrawn')),
  constraint privacy_requests_priority_check check (priority is null or priority in ('normal', 'urgent'))
);

create index privacy_requests_school_id_idx on public.privacy_requests (school_id);
create index privacy_requests_subject_user_id_idx on public.privacy_requests (subject_user_id);
create index privacy_requests_school_created_idx on public.privacy_requests (school_id, created_at desc);

create trigger privacy_requests_set_updated_at before update on public.privacy_requests
  for each row execute function public.set_updated_at();

-- Report
create table public.reports (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  report_type text not null,
  template_name text,
  title text not null,
  academic_year_id uuid references public.academic_years(id) on delete set null,
  term_id uuid references public.terms(id) on delete set null,
  generated_by uuid references public.profiles(id) on delete set null,
  generated_by_name text,
  generated_at timestamptz,
  report_period_start date,
  report_period_end date,
  student_id uuid references public.profiles(id) on delete set null,
  student_name text,
  class_id uuid references public.classes(id) on delete set null,
  class_name text,
  subject_id uuid references public.subjects(id) on delete set null,
  subject_name text,
  report_data jsonb,
  visibility jsonb,
  status text default 'draft',
  approvals jsonb,
  export_formats text[],
  distribution_list jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint reports_report_type_check check (report_type is null or report_type in ('progress_report', 'academic_summary', 'term_report', 'semester_summary', 'ib_progress', 'custom')),
  constraint reports_status_check check (status is null or status in ('draft', 'ready_for_review', 'approved', 'published', 'archived'))
);

create index reports_school_id_idx on public.reports (school_id);
create index reports_academic_year_id_idx on public.reports (academic_year_id);
create index reports_term_id_idx on public.reports (term_id);
create index reports_generated_by_idx on public.reports (generated_by);
create index reports_student_id_idx on public.reports (student_id);
create index reports_class_id_idx on public.reports (class_id);
create index reports_subject_id_idx on public.reports (subject_id);
create index reports_school_created_idx on public.reports (school_id, created_at desc);

create trigger reports_set_updated_at before update on public.reports
  for each row execute function public.set_updated_at();

-- ReportTemplate
create table public.report_templates (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  name text not null,
  description text,
  report_type text not null,
  scope text not null,
  sections jsonb,
  include_sections jsonb,
  grading_display jsonb,
  visibility_rules jsonb,
  is_system_template boolean default false,
  status text default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint report_templates_report_type_check check (report_type is null or report_type in ('progress_report', 'academic_summary', 'term_report', 'semester_summary', 'ib_progress', 'custom')),
  constraint report_templates_scope_check check (scope is null or scope in ('student', 'class', 'subject', 'school')),
  constraint report_templates_status_check check (status is null or status in ('active', 'archived'))
);

create index report_templates_school_id_idx on public.report_templates (school_id);
create index report_templates_school_created_idx on public.report_templates (school_id, created_at desc);

create trigger report_templates_set_updated_at before update on public.report_templates
  for each row execute function public.set_updated_at();

-- RubricTemplate
create table public.rubric_templates (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  name text not null,
  description text,
  subject_group text default 'general',
  level text default 'general',
  criteria jsonb,
  total_max_score numeric,
  is_protected boolean default false,
  protected_reason text,
  status text default 'active',
  usage_count numeric default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint rubric_templates_subject_group_check check (subject_group is null or subject_group in ('group1_language_literature', 'group2_language_acquisition', 'group3_individuals_societies', 'group4_sciences', 'group5_mathematics', 'group6_arts', 'core_tok', 'core_ee', 'core_cas', 'general')),
  constraint rubric_templates_level_check check (level is null or level in ('HL', 'SL', 'MYP', 'core', 'general')),
  constraint rubric_templates_status_check check (status is null or status in ('active', 'archived'))
);

create index rubric_templates_school_id_idx on public.rubric_templates (school_id);
create index rubric_templates_school_created_idx on public.rubric_templates (school_id, created_at desc);

create trigger rubric_templates_set_updated_at before update on public.rubric_templates
  for each row execute function public.set_updated_at();

-- ScheduleEntry
create table public.schedule_entries (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  class_id uuid references public.classes(id) on delete restrict not null,
  class_name text,
  teacher_id uuid references public.profiles(id) on delete set null,
  teacher_name text,
  room_id uuid references public.rooms(id) on delete set null,
  room_name text,
  period_id uuid references public.periods(id) on delete set null,
  day_of_week numeric not null,
  start_time text not null,
  end_time text not null,
  academic_year_id uuid references public.academic_years(id) on delete set null,
  term_id uuid references public.terms(id) on delete set null,
  effective_from date,
  effective_until date,
  status text default 'active',
  external_sync_id text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint schedule_entries_status_check check (status is null or status in ('active', 'cancelled', 'rescheduled'))
);

create index schedule_entries_school_id_idx on public.schedule_entries (school_id);
create index schedule_entries_class_id_idx on public.schedule_entries (class_id);
create index schedule_entries_teacher_id_idx on public.schedule_entries (teacher_id);
create index schedule_entries_room_id_idx on public.schedule_entries (room_id);
create index schedule_entries_period_id_idx on public.schedule_entries (period_id);
create index schedule_entries_academic_year_id_idx on public.schedule_entries (academic_year_id);
create index schedule_entries_term_id_idx on public.schedule_entries (term_id);
create index schedule_entries_school_created_idx on public.schedule_entries (school_id, created_at desc);

create trigger schedule_entries_set_updated_at before update on public.schedule_entries
  for each row execute function public.set_updated_at();

-- SchoolMembership
create table public.school_memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete restrict not null,
  user_email text,
  user_name text,
  school_id uuid references public.schools(id) on delete cascade not null,
  role text not null,
  status text default 'active',
  grade_level text,
  department text,
  permissions text[] default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint school_memberships_role_check check (role is null or role in ('super_admin', 'school_admin', 'ib_coordinator', 'teacher', 'student', 'parent')),
  constraint school_memberships_status_check check (status is null or status in ('active', 'inactive', 'pending'))
);

create index school_memberships_user_id_idx on public.school_memberships (user_id);
create index school_memberships_school_id_idx on public.school_memberships (school_id);
create index school_memberships_school_created_idx on public.school_memberships (school_id, created_at desc);

create trigger school_memberships_set_updated_at before update on public.school_memberships
  for each row execute function public.set_updated_at();

-- SubmissionPolicy
create table public.submission_policies (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  allowed_formats text[] default array['file_upload', 'link', 'google_doc', 'google_slides', 'google_sheet']::text[],
  default_primary_format text,
  allow_teacher_format_override boolean default true,
  late_submission_default text default 'allowed',
  late_penalty_percent numeric default 0,
  late_window_hours numeric default 0,
  allow_teacher_late_override boolean default true,
  allowed_file_extensions text[] default '{}'::text[],
  max_file_size_mb numeric default 50,
  max_files_per_submission numeric default 10,
  retention_days_submissions numeric default 1825,
  retention_days_attachments numeric default 1825,
  plagiarism_flag_enabled boolean default false,
  resubmission_limit numeric default 0,
  show_submission_history_to_student boolean default true,
  show_submission_history_to_teacher boolean default true,
  require_submission_acknowledgement boolean default false,
  acknowledgement_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint submission_policies_default_primary_format_check check (default_primary_format is null or default_primary_format in ('file_upload', 'link', 'google_doc', 'google_slides', 'google_sheet')),
  constraint submission_policies_late_submission_default_check check (late_submission_default is null or late_submission_default in ('allowed', 'blocked', 'penalised'))
);

create index submission_policies_school_id_idx on public.submission_policies (school_id);
create index submission_policies_school_created_idx on public.submission_policies (school_id, created_at desc);

create trigger submission_policies_set_updated_at before update on public.submission_policies
  for each row execute function public.set_updated_at();

-- SupportTicket
create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_id text,
  school text not null,
  subject text not null,
  priority text default 'medium',
  status text default 'open',
  assignee text default 'Unassigned',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint support_tickets_priority_check check (priority is null or priority in ('high', 'medium', 'low')),
  constraint support_tickets_status_check check (status is null or status in ('open', 'in_progress', 'resolved'))
);


create trigger support_tickets_set_updated_at before update on public.support_tickets
  for each row execute function public.set_updated_at();

-- TOKTask
create table public.tok_tasks (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  student_id uuid references public.profiles(id) on delete set null,
  student_name text,
  teacher_id uuid references public.profiles(id) on delete set null,
  teacher_name text,
  title text not null,
  description text,
  task_type text not null,
  due_date date,
  submission_date timestamptz,
  submission_url text,
  submission_text text,
  status text default 'pending',
  teacher_feedback text,
  teacher_feedback_date timestamptz,
  grade text,
  is_class_wide boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint tok_tasks_task_type_check check (task_type is null or task_type in ('exhibition_planning', 'exhibition_draft', 'exhibition_final', 'essay_planning', 'essay_draft', 'essay_final', 'presentation', 'reflection', 'reading', 'other')),
  constraint tok_tasks_status_check check (status is null or status in ('pending', 'submitted', 'reviewed', 'graded'))
);

create index tok_tasks_school_id_idx on public.tok_tasks (school_id);
create index tok_tasks_student_id_idx on public.tok_tasks (student_id);
create index tok_tasks_teacher_id_idx on public.tok_tasks (teacher_id);
create index tok_tasks_school_created_idx on public.tok_tasks (school_id, created_at desc);

create trigger tok_tasks_set_updated_at before update on public.tok_tasks
  for each row execute function public.set_updated_at();

-- TimetableSettings
create table public.timetable_settings (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  external_system_name text,
  external_system_url text,
  external_school_id text,
  sync_enabled boolean default false,
  override_policy text default 'allow_local_edits',
  sync_frequency text default 'manual',
  field_mapping jsonb,
  id_mappings jsonb,
  use_rotating_cycle boolean default false,
  cycle_days text[],
  locked_fields text[],
  show_room_to_students boolean default true,
  show_teacher_to_students boolean default true,
  link_attendance_to_schedule boolean default true,
  last_sync_at timestamptz,
  last_sync_status text default 'never',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint timetable_settings_override_policy_check check (override_policy is null or override_policy in ('read_only', 'allow_local_edits', 'local_override')),
  constraint timetable_settings_sync_frequency_check check (sync_frequency is null or sync_frequency in ('manual', 'hourly', 'daily', 'weekly')),
  constraint timetable_settings_last_sync_status_check check (last_sync_status is null or last_sync_status in ('success', 'failed', 'partial', 'never'))
);

create index timetable_settings_school_id_idx on public.timetable_settings (school_id);
create index timetable_settings_school_created_idx on public.timetable_settings (school_id, created_at desc);

create trigger timetable_settings_set_updated_at before update on public.timetable_settings
  for each row execute function public.set_updated_at();

-- TimetableSync
create table public.timetable_syncs (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  sync_type text not null,
  status text not null default 'pending',
  started_at timestamptz,
  completed_at timestamptz,
  initiated_by text,
  initiated_by_name text,
  records_processed jsonb,
  records_created jsonb,
  records_updated jsonb,
  records_deleted jsonb,
  error_message text,
  error_details jsonb,
  mapping_conflicts jsonb,
  sync_metadata jsonb,
  change_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint timetable_syncs_sync_type_check check (sync_type is null or sync_type in ('full_import', 'incremental_update', 'manual_refresh', 'scheduled_sync')),
  constraint timetable_syncs_status_check check (status is null or status in ('pending', 'in_progress', 'completed', 'failed', 'partial'))
);

create index timetable_syncs_school_id_idx on public.timetable_syncs (school_id);
create index timetable_syncs_school_created_idx on public.timetable_syncs (school_id, created_at desc);

create trigger timetable_syncs_set_updated_at before update on public.timetable_syncs
  for each row execute function public.set_updated_at();

-- UnifiedCalendarEvent
create table public.unified_calendar_events (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  title text not null,
  type text not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  related_entity_id uuid,
  subject_id uuid references public.subjects(id) on delete set null,
  class_id uuid references public.classes(id) on delete set null,
  description text,
  location text,
  created_by_id uuid references public.profiles(id) on delete set null,
  created_by_name text,
  source text default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint unified_calendar_events_type_check check (type is null or type in ('class', 'assignment', 'exam', 'event')),
  constraint unified_calendar_events_source_check check (source is null or source in ('manual', 'internal', 'external'))
);

create index unified_calendar_events_school_id_idx on public.unified_calendar_events (school_id);
create index unified_calendar_events_subject_id_idx on public.unified_calendar_events (subject_id);
create index unified_calendar_events_class_id_idx on public.unified_calendar_events (class_id);
create index unified_calendar_events_created_by_id_idx on public.unified_calendar_events (created_by_id);
create index unified_calendar_events_school_created_idx on public.unified_calendar_events (school_id, created_at desc);

create trigger unified_calendar_events_set_updated_at before update on public.unified_calendar_events
  for each row execute function public.set_updated_at();

-- UserInvitation
create table public.user_invitations (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id) on delete cascade not null,
  email text not null,
  role text not null,
  invited_by text,
  invited_by_name text,
  status text default 'pending',
  invitation_token text not null,
  expires_at timestamptz,
  accepted_at timestamptz,
  user_id uuid references public.profiles(id) on delete set null,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint user_invitations_role_check check (role is null or role in ('school_admin', 'ib_coordinator', 'teacher', 'student', 'parent')),
  constraint user_invitations_status_check check (status is null or status in ('pending', 'accepted', 'expired', 'cancelled'))
);

create index user_invitations_school_id_idx on public.user_invitations (school_id);
create index user_invitations_user_id_idx on public.user_invitations (user_id);
create index user_invitations_school_created_idx on public.user_invitations (school_id, created_at desc);

create trigger user_invitations_set_updated_at before update on public.user_invitations
  for each row execute function public.set_updated_at();

-- deferred FK from 0001
alter table public.profiles
  add constraint profiles_active_school_id_fkey
  foreign key (active_school_id) references public.schools(id) on delete set null;
