-- --------------------------------------------------------------------------
-- 0003 — row level security
--
-- GENERATED by scripts/gen-schema.mjs from the base44 app definition.
-- Do not edit by hand — add a later migration instead.
-- --------------------------------------------------------------------------

-- Every policy below is additive to a global super-admin grant, which mirrors
-- base44's platform-admin bypass. Service-role connections bypass RLS entirely
-- and are what the edge functions use for privileged work.

-- School
alter table public.schools enable row level security;
create policy schools_super_admin on public.schools
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy schools_select on public.schools
  for select to authenticated using ((public.is_member_of(id)
       or public.is_super_admin()));
create policy schools_insert on public.schools
  for insert to authenticated with check (public.is_super_admin());
create policy schools_update on public.schools
  for update to authenticated using ((public.has_school_role(id, array['school_admin'])
       or public.is_super_admin())) with check ((public.has_school_role(id, array['school_admin'])
       or public.is_super_admin()));
create policy schools_delete on public.schools
  for delete to authenticated using (public.is_super_admin());

-- AcademicYear
alter table public.academic_years enable row level security;
create policy academic_years_super_admin on public.academic_years
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy academic_years_select on public.academic_years
  for select to authenticated using (public.is_member_of(school_id));
create policy academic_years_insert on public.academic_years
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy academic_years_update on public.academic_years
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy academic_years_delete on public.academic_years
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- Term
alter table public.terms enable row level security;
create policy terms_super_admin on public.terms
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy terms_select on public.terms
  for select to authenticated using (public.is_member_of(school_id));
create policy terms_insert on public.terms
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy terms_update on public.terms
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy terms_delete on public.terms
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- Subject
alter table public.subjects enable row level security;
create policy subjects_super_admin on public.subjects
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy subjects_select on public.subjects
  for select to authenticated using (public.is_member_of(school_id));
create policy subjects_insert on public.subjects
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy subjects_update on public.subjects
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy subjects_delete on public.subjects
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- Cohort
alter table public.cohorts enable row level security;
create policy cohorts_super_admin on public.cohorts
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy cohorts_select on public.cohorts
  for select to authenticated using (public.is_member_of(school_id));
create policy cohorts_insert on public.cohorts
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy cohorts_update on public.cohorts
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy cohorts_delete on public.cohorts
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- Room
alter table public.rooms enable row level security;
create policy rooms_super_admin on public.rooms
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy rooms_select on public.rooms
  for select to authenticated using (public.is_member_of(school_id));
create policy rooms_insert on public.rooms
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy rooms_update on public.rooms
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy rooms_delete on public.rooms
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- Period
alter table public.periods enable row level security;
create policy periods_super_admin on public.periods
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy periods_select on public.periods
  for select to authenticated using (public.is_member_of(school_id));
create policy periods_insert on public.periods
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy periods_update on public.periods
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy periods_delete on public.periods
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- Class
alter table public.classes enable row level security;
create policy classes_super_admin on public.classes
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy classes_select on public.classes
  for select to authenticated using (public.is_member_of(school_id));
create policy classes_insert on public.classes
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy classes_update on public.classes
  for update to authenticated using (public.is_member_of(school_id)) with check (public.is_member_of(school_id));
create policy classes_delete on public.classes
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- CurriculumTopic
alter table public.curriculum_topics enable row level security;
create policy curriculum_topics_super_admin on public.curriculum_topics
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy curriculum_topics_select on public.curriculum_topics
  for select to authenticated using (public.is_member_of(school_id));
create policy curriculum_topics_insert on public.curriculum_topics
  for insert to authenticated with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy curriculum_topics_update on public.curriculum_topics
  for update to authenticated using (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy curriculum_topics_delete on public.curriculum_topics
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- Assignment
alter table public.assignments enable row level security;
create policy assignments_super_admin on public.assignments
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy assignments_select on public.assignments
  for select to authenticated using (public.is_member_of(school_id));
create policy assignments_insert on public.assignments
  for insert to authenticated with check ((public.is_member_of(school_id)
     and teacher_id = auth.uid()));
create policy assignments_update on public.assignments
  for update to authenticated using ((public.is_member_of(school_id)
     and teacher_id = auth.uid())) with check ((public.is_member_of(school_id)
     and teacher_id = auth.uid()));
create policy assignments_delete on public.assignments
  for delete to authenticated using ((public.is_member_of(school_id)
     and teacher_id = auth.uid()));

-- Assessment
alter table public.assessments enable row level security;
create policy assessments_super_admin on public.assessments
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy assessments_select on public.assessments
  for select to authenticated using (public.is_member_of(school_id));
create policy assessments_insert on public.assessments
  for insert to authenticated with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy assessments_update on public.assessments
  for update to authenticated using (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy assessments_delete on public.assessments
  for delete to authenticated using (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));

-- Submission
alter table public.submissions enable row level security;
create policy submissions_super_admin on public.submissions
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy submissions_select on public.submissions
  for select to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']))));
create policy submissions_insert on public.submissions
  for insert to authenticated with check ((public.is_member_of(school_id)
     and student_id = auth.uid()));
create policy submissions_update on public.submissions
  for update to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']))));
create policy submissions_delete on public.submissions
  for delete to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));

-- AccountState
alter table public.account_states enable row level security;
create policy account_states_super_admin on public.account_states
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy account_states_select on public.account_states
  for select to authenticated using ((user_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])));
create policy account_states_insert on public.account_states
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy account_states_update on public.account_states
  for update to authenticated using ((user_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))) with check ((user_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])));
create policy account_states_delete on public.account_states
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- AssessmentSubmission
alter table public.assessment_submissions enable row level security;
create policy assessment_submissions_super_admin on public.assessment_submissions
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy assessment_submissions_select on public.assessment_submissions
  for select to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']))));
create policy assessment_submissions_insert on public.assessment_submissions
  for insert to authenticated with check ((public.is_member_of(school_id)
     and student_id = auth.uid()));
create policy assessment_submissions_update on public.assessment_submissions
  for update to authenticated using ((public.is_member_of(school_id)
     and ((student_id = auth.uid()
     and locked = false)
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and ((student_id = auth.uid()
     and locked = false)
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']))));
create policy assessment_submissions_delete on public.assessment_submissions
  for delete to authenticated using (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));

-- AttendancePolicy
alter table public.attendance_policies enable row level security;
create policy attendance_policies_super_admin on public.attendance_policies
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy attendance_policies_select on public.attendance_policies
  for select to authenticated using (public.is_member_of(school_id));
create policy attendance_policies_insert on public.attendance_policies
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin']));
create policy attendance_policies_update on public.attendance_policies
  for update to authenticated using (public.has_school_role(school_id, array['school_admin'])) with check (public.has_school_role(school_id, array['school_admin']));
create policy attendance_policies_delete on public.attendance_policies
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- AttendanceRecord
alter table public.attendance_records enable row level security;
create policy attendance_records_super_admin on public.attendance_records
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy attendance_records_select on public.attendance_records
  for select to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']))));
create policy attendance_records_insert on public.attendance_records
  for insert to authenticated with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy attendance_records_update on public.attendance_records
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy attendance_records_delete on public.attendance_records
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- AuditLog
alter table public.audit_logs enable row level security;
create policy audit_logs_super_admin on public.audit_logs
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy audit_logs_select on public.audit_logs
  for select to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
-- create: super-admin only (base44 declared no rule)
-- update: super-admin only (base44 declared no rule)
-- delete: super-admin only (base44 declared no rule)

-- BehaviorPolicy
alter table public.behavior_policies enable row level security;
create policy behavior_policies_super_admin on public.behavior_policies
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy behavior_policies_select on public.behavior_policies
  for select to authenticated using (public.is_member_of(school_id));
create policy behavior_policies_insert on public.behavior_policies
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin']));
create policy behavior_policies_update on public.behavior_policies
  for update to authenticated using (public.has_school_role(school_id, array['school_admin'])) with check (public.has_school_role(school_id, array['school_admin']));
create policy behavior_policies_delete on public.behavior_policies
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- BehaviorRecord
alter table public.behavior_records enable row level security;
create policy behavior_records_super_admin on public.behavior_records
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy behavior_records_select on public.behavior_records
  for select to authenticated using ((public.is_member_of(school_id)
     and ((student_id = auth.uid()
     and visible_to_student = true)
       or public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']))));
create policy behavior_records_insert on public.behavior_records
  for insert to authenticated with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy behavior_records_update on public.behavior_records
  for update to authenticated using ((public.is_member_of(school_id)
     and (created_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (created_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy behavior_records_delete on public.behavior_records
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- CASExperience
alter table public.cas_experiences enable row level security;
create policy cas_experiences_super_admin on public.cas_experiences
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy cas_experiences_select on public.cas_experiences
  for select to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy cas_experiences_insert on public.cas_experiences
  for insert to authenticated with check ((public.is_member_of(school_id)
     and student_id = auth.uid()));
create policy cas_experiences_update on public.cas_experiences
  for update to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy cas_experiences_delete on public.cas_experiences
  for delete to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));

-- ClassMaterial
alter table public.class_materials enable row level security;
create policy class_materials_super_admin on public.class_materials
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy class_materials_select on public.class_materials
  for select to authenticated using (public.is_member_of(school_id));
create policy class_materials_insert on public.class_materials
  for insert to authenticated with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy class_materials_update on public.class_materials
  for update to authenticated using ((public.is_member_of(school_id)
     and (uploaded_by_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (uploaded_by_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy class_materials_delete on public.class_materials
  for delete to authenticated using ((public.is_member_of(school_id)
     and (uploaded_by_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));

-- DemoRequest
alter table public.demo_requests enable row level security;
create policy demo_requests_super_admin on public.demo_requests
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
-- Public lead-capture form, submitted while signed out. Write-only — leads are readable by super admins alone.
-- base44 had NO rls on this entity; policy written from scratch.
create policy demo_requests_select on public.demo_requests
  for select to authenticated using (public.is_super_admin());
create policy demo_requests_insert on public.demo_requests
  for insert to anon, authenticated with check (true);

-- EEMilestone
alter table public.ee_milestones enable row level security;
create policy ee_milestones_super_admin on public.ee_milestones
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy ee_milestones_select on public.ee_milestones
  for select to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or supervisor_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy ee_milestones_insert on public.ee_milestones
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy ee_milestones_update on public.ee_milestones
  for update to authenticated using ((public.is_member_of(school_id)
     and (supervisor_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (supervisor_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy ee_milestones_delete on public.ee_milestones
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- ErrorLog
alter table public.error_logs enable row level security;
create policy error_logs_super_admin on public.error_logs
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
-- Write-only for everyone including signed-out visitors; only super admins read.
-- base44 had NO rls on this entity; policy written from scratch.
create policy error_logs_select on public.error_logs
  for select to authenticated using (public.is_super_admin());
create policy error_logs_insert on public.error_logs
  for insert to anon, authenticated with check (true);

-- GoogleConnection
alter table public.google_connections enable row level security;
create policy google_connections_super_admin on public.google_connections
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
-- OAuth access + refresh tokens — owner only. Server-side refresh uses the service role.
-- base44 had NO rls on this entity; policy written from scratch.
create policy google_connections_select on public.google_connections
  for select to authenticated using (user_id = auth.uid());
create policy google_connections_insert on public.google_connections
  for insert to authenticated with check (user_id = auth.uid());
create policy google_connections_update on public.google_connections
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy google_connections_delete on public.google_connections
  for delete to authenticated using (user_id = auth.uid());

-- GovernancePolicy
alter table public.governance_policies enable row level security;
create policy governance_policies_super_admin on public.governance_policies
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy governance_policies_select on public.governance_policies
  for select to authenticated using (public.is_member_of(school_id));
create policy governance_policies_insert on public.governance_policies
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin']));
create policy governance_policies_update on public.governance_policies
  for update to authenticated using (public.has_school_role(school_id, array['school_admin'])) with check (public.has_school_role(school_id, array['school_admin']));
create policy governance_policies_delete on public.governance_policies
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- GradeItem
alter table public.grade_items enable row level security;
create policy grade_items_super_admin on public.grade_items
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy grade_items_select on public.grade_items
  for select to authenticated using ((public.is_member_of(school_id)
     and ((student_id = auth.uid()
     and visible_to_student = true)
       or visible_to_parent = true
       or created_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy grade_items_insert on public.grade_items
  for insert to authenticated with check ((public.is_member_of(school_id)
     and created_by = auth.uid()));
create policy grade_items_update on public.grade_items
  for update to authenticated using ((public.is_member_of(school_id)
     and (created_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (created_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy grade_items_delete on public.grade_items
  for delete to authenticated using ((public.is_member_of(school_id)
     and (created_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));

-- GradebookPolicy
alter table public.gradebook_policies enable row level security;
create policy gradebook_policies_super_admin on public.gradebook_policies
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy gradebook_policies_select on public.gradebook_policies
  for select to authenticated using (public.is_member_of(school_id));
create policy gradebook_policies_insert on public.gradebook_policies
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin']));
create policy gradebook_policies_update on public.gradebook_policies
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy gradebook_policies_delete on public.gradebook_policies
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- LessonPlan
alter table public.lesson_plans enable row level security;
create policy lesson_plans_super_admin on public.lesson_plans
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy lesson_plans_select on public.lesson_plans
  for select to authenticated using ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy lesson_plans_insert on public.lesson_plans
  for insert to authenticated with check ((public.is_member_of(school_id)
     and teacher_id = auth.uid()));
create policy lesson_plans_update on public.lesson_plans
  for update to authenticated using ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy lesson_plans_delete on public.lesson_plans
  for delete to authenticated using ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));

-- Message
alter table public.messages enable row level security;
create policy messages_super_admin on public.messages
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy messages_select on public.messages
  for select to authenticated using ((public.is_member_of(school_id)
     and (sender_id = auth.uid()
       or auth.uid() = any(recipient_ids)
       or public.is_super_admin())));
create policy messages_insert on public.messages
  for insert to authenticated with check (public.is_member_of(school_id));
create policy messages_update on public.messages
  for update to authenticated using (sender_id = auth.uid()) with check (sender_id = auth.uid());
create policy messages_delete on public.messages
  for delete to authenticated using (sender_id = auth.uid());

-- MessagingPolicy
alter table public.messaging_policies enable row level security;
create policy messaging_policies_super_admin on public.messaging_policies
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy messaging_policies_select on public.messaging_policies
  for select to authenticated using (public.is_member_of(school_id));
create policy messaging_policies_insert on public.messaging_policies
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin']));
create policy messaging_policies_update on public.messaging_policies
  for update to authenticated using (public.has_school_role(school_id, array['school_admin'])) with check (public.has_school_role(school_id, array['school_admin']));
create policy messaging_policies_delete on public.messaging_policies
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- Notification
alter table public.notifications enable row level security;
create policy notifications_super_admin on public.notifications
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy notifications_select on public.notifications
  for select to authenticated using ((user_id = auth.uid()
       or public.is_super_admin()));
-- create: super-admin only (base44 declared no rule)
create policy notifications_update on public.notifications
  for update to authenticated using ((user_id = auth.uid()
       or public.is_super_admin())) with check ((user_id = auth.uid()
       or public.is_super_admin()));
create policy notifications_delete on public.notifications
  for delete to authenticated using ((user_id = auth.uid()
       or public.is_super_admin()));

-- ParentStudentLink
alter table public.parent_student_links enable row level security;
create policy parent_student_links_super_admin on public.parent_student_links
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy parent_student_links_select on public.parent_student_links
  for select to authenticated using ((public.is_member_of(school_id)
     and (parent_id = auth.uid()
       or student_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator', 'teacher']))));
create policy parent_student_links_insert on public.parent_student_links
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy parent_student_links_update on public.parent_student_links
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy parent_student_links_delete on public.parent_student_links
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- PlatformConfig
alter table public.platform_config enable row level security;
create policy platform_config_super_admin on public.platform_config
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
-- Readable by any signed-in user; writable by super admins only.
-- base44 had NO rls on this entity; policy written from scratch.
create policy platform_config_select on public.platform_config
  for select to authenticated using (true);
create policy platform_config_insert on public.platform_config
  for insert to authenticated with check (public.is_super_admin());
create policy platform_config_update on public.platform_config
  for update to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy platform_config_delete on public.platform_config
  for delete to authenticated using (public.is_super_admin());

-- PredictedGrade
alter table public.predicted_grades enable row level security;
create policy predicted_grades_super_admin on public.predicted_grades
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy predicted_grades_select on public.predicted_grades
  for select to authenticated using ((public.is_member_of(school_id)
     and ((student_id = auth.uid()
     and visible_to_student = true)
       or visible_to_parent = true
       or teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy predicted_grades_insert on public.predicted_grades
  for insert to authenticated with check ((public.is_member_of(school_id)
     and teacher_id = auth.uid()));
create policy predicted_grades_update on public.predicted_grades
  for update to authenticated using ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy predicted_grades_delete on public.predicted_grades
  for delete to authenticated using ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));

-- PrivacyRequest
alter table public.privacy_requests enable row level security;
create policy privacy_requests_super_admin on public.privacy_requests
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
-- GDPR requests — school admins manage them; the data subject can read and raise their own.
-- base44 had NO rls on this entity; policy written from scratch.
create policy privacy_requests_select on public.privacy_requests
  for select to authenticated using ((public.has_school_role(school_id, array['school_admin']) or subject_user_id = auth.uid()));
create policy privacy_requests_insert on public.privacy_requests
  for insert to authenticated with check (public.is_member_of(school_id));
create policy privacy_requests_update on public.privacy_requests
  for update to authenticated using (public.has_school_role(school_id, array['school_admin'])) with check (public.has_school_role(school_id, array['school_admin']));
create policy privacy_requests_delete on public.privacy_requests
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- Report
alter table public.reports enable row level security;
create policy reports_super_admin on public.reports
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy reports_select on public.reports
  for select to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or generated_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy reports_insert on public.reports
  for insert to authenticated with check ((public.is_member_of(school_id)
     and generated_by = auth.uid()));
create policy reports_update on public.reports
  for update to authenticated using ((public.is_member_of(school_id)
     and (generated_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (generated_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy reports_delete on public.reports
  for delete to authenticated using ((public.is_member_of(school_id)
     and (generated_by = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));

-- ReportTemplate
alter table public.report_templates enable row level security;
create policy report_templates_super_admin on public.report_templates
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy report_templates_select on public.report_templates
  for select to authenticated using (public.is_member_of(school_id));
create policy report_templates_insert on public.report_templates
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy report_templates_update on public.report_templates
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy report_templates_delete on public.report_templates
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- RubricTemplate
alter table public.rubric_templates enable row level security;
create policy rubric_templates_super_admin on public.rubric_templates
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy rubric_templates_select on public.rubric_templates
  for select to authenticated using (public.is_member_of(school_id));
create policy rubric_templates_insert on public.rubric_templates
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy rubric_templates_update on public.rubric_templates
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy rubric_templates_delete on public.rubric_templates
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- ScheduleEntry
alter table public.schedule_entries enable row level security;
create policy schedule_entries_super_admin on public.schedule_entries
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy schedule_entries_select on public.schedule_entries
  for select to authenticated using (public.is_member_of(school_id));
create policy schedule_entries_insert on public.schedule_entries
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy schedule_entries_update on public.schedule_entries
  for update to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));
create policy schedule_entries_delete on public.schedule_entries
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin', 'ib_coordinator']));

-- SchoolMembership
alter table public.school_memberships enable row level security;
create policy school_memberships_super_admin on public.school_memberships
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy school_memberships_select on public.school_memberships
  for select to authenticated using (public.is_member_of(school_id));
create policy school_memberships_insert on public.school_memberships
  for insert to authenticated with check (public.is_super_admin());
create policy school_memberships_update on public.school_memberships
  for update to authenticated using ((public.is_super_admin()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))) with check ((public.is_super_admin()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])));
create policy school_memberships_delete on public.school_memberships
  for delete to authenticated using ((public.is_super_admin()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])));

-- SubmissionPolicy
alter table public.submission_policies enable row level security;
create policy submission_policies_super_admin on public.submission_policies
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy submission_policies_select on public.submission_policies
  for select to authenticated using (public.is_member_of(school_id));
create policy submission_policies_insert on public.submission_policies
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin']));
create policy submission_policies_update on public.submission_policies
  for update to authenticated using (public.has_school_role(school_id, array['school_admin'])) with check (public.has_school_role(school_id, array['school_admin']));
create policy submission_policies_delete on public.submission_policies
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- SupportTicket
alter table public.support_tickets enable row level security;
create policy support_tickets_super_admin on public.support_tickets
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
-- Raised from inside the app. Write-only; only super admins read.
-- base44 had NO rls on this entity; policy written from scratch.
create policy support_tickets_select on public.support_tickets
  for select to authenticated using (public.is_super_admin());
create policy support_tickets_insert on public.support_tickets
  for insert to authenticated with check (true);

-- TOKTask
alter table public.tok_tasks enable row level security;
create policy tok_tasks_super_admin on public.tok_tasks
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy tok_tasks_select on public.tok_tasks
  for select to authenticated using ((public.is_member_of(school_id)
     and (student_id = auth.uid()
       or teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy tok_tasks_insert on public.tok_tasks
  for insert to authenticated with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy tok_tasks_update on public.tok_tasks
  for update to authenticated using ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])))) with check ((public.is_member_of(school_id)
     and (teacher_id = auth.uid()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))));
create policy tok_tasks_delete on public.tok_tasks
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- TimetableSettings
alter table public.timetable_settings enable row level security;
create policy timetable_settings_super_admin on public.timetable_settings
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy timetable_settings_select on public.timetable_settings
  for select to authenticated using (public.is_member_of(school_id));
create policy timetable_settings_insert on public.timetable_settings
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin']));
create policy timetable_settings_update on public.timetable_settings
  for update to authenticated using (public.has_school_role(school_id, array['school_admin'])) with check (public.has_school_role(school_id, array['school_admin']));
create policy timetable_settings_delete on public.timetable_settings
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin']));

-- TimetableSync
alter table public.timetable_syncs enable row level security;
create policy timetable_syncs_super_admin on public.timetable_syncs
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
-- base44 had NO rls on this entity; policy written from scratch.
create policy timetable_syncs_select on public.timetable_syncs
  for select to authenticated using (public.is_member_of(school_id));
create policy timetable_syncs_insert on public.timetable_syncs
  for insert to authenticated with check (public.has_school_role(school_id, array['school_admin','ib_coordinator']));
create policy timetable_syncs_update on public.timetable_syncs
  for update to authenticated using (public.has_school_role(school_id, array['school_admin','ib_coordinator'])) with check (public.has_school_role(school_id, array['school_admin','ib_coordinator']));
create policy timetable_syncs_delete on public.timetable_syncs
  for delete to authenticated using (public.has_school_role(school_id, array['school_admin','ib_coordinator']));

-- UnifiedCalendarEvent
alter table public.unified_calendar_events enable row level security;
create policy unified_calendar_events_super_admin on public.unified_calendar_events
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy unified_calendar_events_select on public.unified_calendar_events
  for select to authenticated using (public.is_member_of(school_id));
create policy unified_calendar_events_insert on public.unified_calendar_events
  for insert to authenticated with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy unified_calendar_events_update on public.unified_calendar_events
  for update to authenticated using (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator'])) with check (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));
create policy unified_calendar_events_delete on public.unified_calendar_events
  for delete to authenticated using (public.has_school_role(school_id, array['teacher', 'school_admin', 'ib_coordinator']));

-- UserInvitation
alter table public.user_invitations enable row level security;
create policy user_invitations_super_admin on public.user_invitations
  for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy user_invitations_select on public.user_invitations
  for select to authenticated using ((public.is_super_admin()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])));
create policy user_invitations_insert on public.user_invitations
  for insert to authenticated with check ((public.is_super_admin()
       or public.current_app_role() in ('school_admin', 'ib_coordinator')));
create policy user_invitations_update on public.user_invitations
  for update to authenticated using ((public.is_super_admin()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator']))) with check ((public.is_super_admin()
       or public.has_school_role(school_id, array['school_admin', 'ib_coordinator'])));
create policy user_invitations_delete on public.user_invitations
  for delete to authenticated using ((public.is_super_admin()
       or public.has_school_role(school_id, array['school_admin'])));

