import { Group } from '@/components/app/AppShell';
import StatCard from '@/components/app/StatCard';
import Notice from '@/components/app/Notice';
import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Save, Loader2, Archive, Database, Clock, HardDrive } from 'lucide-react';
import * as attendanceData from '@/data/attendance';
import * as behaviorRecordsData from '@/data/behaviorRecords';
import * as admin from '@/data/admin';
import * as submissionsData from '@/data/submissions';

const RETENTION_FIELDS = [
  {
    key: 'archived_class_data_days',
    label: 'Archived class data',
    description: 'Grade items, assignment records, and enrollment data for classes marked as archived.',
    icon: Archive,
    recommended: '1825 (5 years)',
  },
  {
    key: 'submission_files_days',
    label: 'Student submission files',
    description: 'Uploaded files, Google Drive attachments, and document links submitted by students.',
    icon: HardDrive,
    recommended: '1825 (5 years)',
  },
  {
    key: 'attendance_records_days',
    label: 'Attendance records',
    description: 'All attendance data including corrections and correction history.',
    icon: Clock,
    recommended: '2555 (7 years)',
  },
  {
    key: 'behavior_records_days',
    label: 'Behaviour & pastoral records',
    description: 'Student behaviour records, pastoral notes, follow-ups, and review outcomes.',
    icon: Database,
    recommended: '1825 (5 years)',
  },
  {
    key: 'audit_log_days',
    label: 'Audit log entries',
    description: 'School-level audit trail entries generated by staff actions.',
    icon: Database,
    recommended: '730 (2 years)',
  },
  {
    key: 'message_metadata_days',
    label: 'Message metadata',
    description: 'Message send/receive metadata (not message content). Stored for compliance only.',
    icon: Database,
    recommended: '365 (1 year)',
  },
];

function RetentionField({ field, value, onChange }) {
  return (
    <div style={{ padding: '.8rem .9rem', borderTop: '1px solid var(--rule-soft)' }}>
      <div className="flex items-start gap-3">
        <div className="flex-1 min-w-0">
          <p className="font-semibold scholr-ink text-sm">{field.label}</p>
          <p className="text-xs scholr-muted mt-0.5 mb-3">{field.description}</p>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <Input
                type="number"
                min={30}
                max={9999}
                className="w-24 h-8 text-sm"
                value={value || ''}
                onChange={e => onChange(field.key, Number(e.target.value))}
              />
              <span className="text-xs scholr-muted">days</span>
            </div>
            <span className="text-xs scholr-faint">Recommended: {field.recommended} days</span>
          </div>
          {value > 0 && (
            <p className="text-xs scholr-faint mt-1">
              ≈ {(value / 365).toFixed(1)} years · Records older than this threshold are eligible for archival review
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

export default function DataRetentionPanel({ policy, onChange, onSave, saving, schoolId }) {
  const retention = policy?.retention || {};

  const handleChange = (key, value) => {
    onChange({ retention: { ...retention, [key]: value } });
  };

  const { data: stats } = useQuery({
    queryKey: ['governance-data-stats', schoolId],
    queryFn: async () => {
      const [attendance, behavior, auditLogs, submissions] = await Promise.all([
        attendanceData.countForSchool(schoolId),
        behaviorRecordsData.countForSchool(schoolId),
        admin.countAuditLogs({ schoolId }),
        submissionsData.countForSchool(schoolId),
      ]);
      return { attendance, behavior, auditLogs, submissions };
    },
    enabled: !!schoolId,
  });

  return (
    <div className="space-y-5">
      <Notice title="Nothing is deleted automatically">
        A retention period says how long a kind of record is kept before it becomes eligible for review
        or archival. Zero means keep it indefinitely. Purging is always started by a person.
      </Notice>

      {/* Live data stats */}
      {stats && (
        <Group title="How much you are holding">
          <div className="scholr-grid app-cols-4">
            <StatCard label="Attendance" value={stats.attendance.toLocaleString()} hint="records" />
            <StatCard label="Behaviour" value={stats.behavior.toLocaleString()} hint="records" />
            <StatCard label="Submissions" value={stats.submissions.toLocaleString()} hint="files and entries" />
            <StatCard label="Audit log" value={stats.auditLogs.toLocaleString()} hint="entries" />
          </div>
        </Group>
      )}

      {/* Retention fields */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-semibold scholr-faint uppercase tracking-wide">Retention Periods</p>
          <Button onClick={onSave} disabled={saving} size="sm" className="scholr-accent-sf hover:scholr-accent-sf gap-1.5">
            {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />}
            Save Retention Policy
          </Button>
        </div>
        <div className="app-group">
          {RETENTION_FIELDS.map(field => (
            <RetentionField
              key={field.key}
              field={field}
              value={retention[field.key] ?? 0}
              onChange={handleChange}
            />
          ))}
        </div>
      </div>

      {/* Inactive account purge */}
      <div className="app-group" style={{ padding: '1rem 1.1rem' }}>
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="font-semibold scholr-ink text-sm">Inactive Account Flagging</p>
            <p className="text-xs scholr-muted mt-1">Automatically flag deactivated accounts for review after a set number of days. Admins receive a notification; no data is deleted without manual confirmation.</p>
            <div className="flex items-center gap-3 mt-3">
              <Input
                type="number"
                min={0}
                className="w-24 h-8 text-sm"
                value={retention.purge_inactive_accounts_days || 0}
                onChange={e => handleChange('purge_inactive_accounts_days', Number(e.target.value))}
              />
              <span className="text-xs scholr-muted">days after deactivation (0 = disabled)</span>
            </div>
          </div>
          <Switch
            checked={(retention.purge_inactive_accounts_days || 0) > 0}
            onCheckedChange={v => handleChange('purge_inactive_accounts_days', v ? 365 : 0)}
          />
        </div>
      </div>
    </div>
  );
}