import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Save, Loader2, Info, Archive, Database, Clock, HardDrive } from 'lucide-react';
import * as attendanceData from '@/data/attendance';
import * as behaviorRecordsData from '@/data/behaviorRecords';
import * as admin from '@/data/admin';
import * as submissionsData from '@/data/submissions';

const RETENTION_FIELDS = [
  {
    key: 'archived_class_data_days',
    label: 'Archived class data',
    description: 'Grade items, assignment records, and enrollment data for classes marked as archived.',
    icon: Archive,
    recommended: '1825 (5 years)',
    color: 'text-indigo-600 bg-indigo-50',
  },
  {
    key: 'submission_files_days',
    label: 'Student submission files',
    description: 'Uploaded files, Google Drive attachments, and document links submitted by students.',
    icon: HardDrive,
    recommended: '1825 (5 years)',
    color: 'text-violet-600 bg-violet-50',
  },
  {
    key: 'attendance_records_days',
    label: 'Attendance records',
    description: 'All attendance data including corrections and correction history.',
    icon: Clock,
    recommended: '2555 (7 years)',
    color: 'text-emerald-600 bg-emerald-50',
  },
  {
    key: 'behavior_records_days',
    label: 'Behaviour & pastoral records',
    description: 'Student behaviour records, pastoral notes, follow-ups, and review outcomes.',
    icon: Database,
    recommended: '1825 (5 years)',
    color: 'text-amber-600 bg-amber-50',
  },
  {
    key: 'audit_log_days',
    label: 'Audit log entries',
    description: 'School-level audit trail entries generated by staff actions.',
    icon: Database,
    recommended: '730 (2 years)',
    color: 'text-sky-600 bg-sky-50',
  },
  {
    key: 'message_metadata_days',
    label: 'Message metadata',
    description: 'Message send/receive metadata (not message content). Stored for compliance only.',
    icon: Database,
    recommended: '365 (1 year)',
    color: 'text-rose-600 bg-rose-50',
  },
];

function RetentionField({ field, value, onChange }) {
  const Icon = field.icon;
  return (
    <div className="bg-white rounded-xl border border-slate-200 p-4">
      <div className="flex items-start gap-3">
        <div className={`rounded-lg p-2 shrink-0 ${field.color}`}>
          <Icon className="w-4 h-4" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="font-semibold text-slate-800 text-sm">{field.label}</p>
          <p className="text-xs text-slate-500 mt-0.5 mb-3">{field.description}</p>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <Input
                type="number"
                min={30}
                max={9999}
                className="w-24 h-8 text-sm"
                value={value || ''}
                onChange={e => onChange(field.key, Number(e.target.value))}
              />
              <span className="text-xs text-slate-500">days</span>
            </div>
            <span className="text-xs text-slate-400">Recommended: {field.recommended} days</span>
          </div>
          {value > 0 && (
            <p className="text-xs text-slate-400 mt-1">
              ≈ {(value / 365).toFixed(1)} years · Records older than this threshold are eligible for archival review
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

export default function DataRetentionPanel({ policy, onChange, onSave, saving, schoolId }) {
  const retention = policy?.retention || {};

  const handleChange = (key, value) => {
    onChange({ retention: { ...retention, [key]: value } });
  };

  const { data: stats } = useQuery({
    queryKey: ['governance-data-stats', schoolId],
    queryFn: async () => {
      const [attendance, behavior, auditLogs, submissions] = await Promise.all([
        attendanceData.whereRecords({ school_id: schoolId }),
        behaviorRecordsData.where({ school_id: schoolId }),
        admin.whereAuditLogs({ school_id: schoolId }),
        submissionsData.where({ school_id: schoolId }),
      ]);
      return { attendance: attendance.length, behavior: behavior.length, auditLogs: auditLogs.length, submissions: submissions.length };
    },
    enabled: !!schoolId,
  });

  return (
    <div className="space-y-5">
      <div className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-3 flex gap-2 text-sm text-amber-800">
        <Info className="w-4 h-4 shrink-0 mt-0.5" />
        <p>Retention periods define how long each category of data is preserved before it becomes eligible for review or archival. Setting a value of <strong>0</strong> means the data is retained indefinitely. Actual purging must be initiated manually by an admin — the system does not automatically delete data.</p>
      </div>

      {/* Live data stats */}
      {stats && (
        <div>
          <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-3">Current Data Volumes</p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { label: 'Attendance Records', value: stats.attendance, color: 'text-emerald-700 bg-emerald-50 border-emerald-200' },
              { label: 'Behaviour Records', value: stats.behavior, color: 'text-amber-700 bg-amber-50 border-amber-200' },
              { label: 'Submissions', value: stats.submissions, color: 'text-violet-700 bg-violet-50 border-violet-200' },
              { label: 'Audit Log Entries', value: stats.auditLogs, color: 'text-sky-700 bg-sky-50 border-sky-200' },
            ].map(({ label, value, color }) => (
              <div key={label} className={`border rounded-lg p-3 text-center ${color}`}>
                <p className="text-xl font-bold">{value.toLocaleString()}</p>
                <p className="text-xs mt-0.5">{label}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Retention fields */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-semibold text-slate-400 uppercase tracking-wide">Retention Periods</p>
          <Button onClick={onSave} disabled={saving} size="sm" className="bg-indigo-600 hover:bg-indigo-700 gap-1.5">
            {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />}
            Save Retention Policy
          </Button>
        </div>
        <div className="space-y-3">
          {RETENTION_FIELDS.map(field => (
            <RetentionField
              key={field.key}
              field={field}
              value={retention[field.key] ?? 0}
              onChange={handleChange}
            />
          ))}
        </div>
      </div>

      {/* Inactive account purge */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="font-semibold text-slate-800 text-sm">Inactive Account Flagging</p>
            <p className="text-xs text-slate-500 mt-1">Automatically flag deactivated accounts for review after a set number of days. Admins receive a notification; no data is deleted without manual confirmation.</p>
            <div className="flex items-center gap-3 mt-3">
              <Input
                type="number"
                min={0}
                className="w-24 h-8 text-sm"
                value={retention.purge_inactive_accounts_days || 0}
                onChange={e => handleChange('purge_inactive_accounts_days', Number(e.target.value))}
              />
              <span className="text-xs text-slate-500">days after deactivation (0 = disabled)</span>
            </div>
          </div>
          <Switch
            checked={(retention.purge_inactive_accounts_days || 0) > 0}
            onCheckedChange={v => handleChange('purge_inactive_accounts_days', v ? 365 : 0)}
          />
        </div>
      </div>
    </div>
  );
}